### ISSUE TITLE
terracli.md

### ISSUE THREAD

**Issue by EdouardLvdl** [terra-project/core#126]
--amount and --validator are unknown flags for

terracli tx staking delegate \
  --amount=10luna \
  --validator=<validator> \
  --from=<key_name> \
  --chain-id=<chain_id>

Shouldn't it be?
terracli tx staking delegate [validator] [amount]
  --from=<key_name> \
  --chain-id=<chain_id>

**Comment by hanjukim** [comment]
Yes it should be fixed.

**Comment by YunSuk-Yeo** [comment]
Fixed by #127 .
