### ISSUE TITLE
Terrad can't start

### ISSUE THREAD

**Issue by mymixing** [terra-project/core#131]
How to start the terrad main network
Startup error now:

[2019-05-08|11:44:32.079] Starting ABCI with Tendermint                module=main 
ERROR: Error during handshake: Error on replay: Validator set is nil in genesis and still empty after InitChain

**Comment by YunSuk-Yeo** [comment]
you have to replace genesis.json in ~/.terrad/config/ to mainnet [genesis](https://raw.githubusercontent.com/terra-project/launch/master/genesis.json). 

And type `$ terrad unsafe-reset-all`

You also fill the seeds and persistent_peers in ~/.terrad/config/config.toml with [this](https://github.com/terra-project/launch#seed-nodes)

**Comment by changwu-tw** [comment]
It works!
