### ISSUE TITLE
terrad still can't start

### ISSUE THREAD

**Issue by mymixing** [terra-project/core#137]
the error is like this:
[2019-05-09|16:25:32.622] Starting ABCI with Tendermint                module=main 
ERROR: Block.MaxBytes must be greater than 0. Got 0

but I can't find related fields from "config.toml" and "genesis.json"

**Comment by YunSuk-Yeo** [comment]
Which version are you using? You should [v0.1.1](https://github.com/terra-project/core/releases/tag/v0.1.1)

**Comment by mymixing** [comment]
@YunSuk-Yeo 
my version

[root@Wallet-DEMO-4 ~/go/bin]$ terrad version
0.1.1-1-gd6341ad

**Comment by YunSuk-Yeo** [comment]
Is your genesis file [genesis.json](https://raw.githubusercontent.com/terra-project/launch/master/genesis.json)? It has consensus_params.block.max_bytes. If you using same genesis, try one more `$terrad unsafe-reset-all`

**Comment by mymixing** [comment]
@YunSuk-Yeo 
the problem has been solved
my mistake is because I used it.
terrad --home
--home parameter does not take effect
thank you.
