### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by jonchoi** [terra-project/core#145]
Following the guide here: https://docs.terra.money/guide/installation

> --> Download go modules to local cache
make: statik: No such file or directory
make: *** [update_terra_lite_docs] Error 1

**Comment by YunSuk-Yeo** [comment]
You need to configure $GOPATH, $GOROOT, and $GOBIN for go build. @jonchoi

**Comment by jonchoi** [comment]
Works. Thanks!
