### ISSUE TITLE
Change SMR computation in updateRewardPolicy

### ISSUE THREAD

**Issue by nplatias** [terra-project/core#17]
## **Summary**
smrAvgMonth is currently computed as the rolling average of individual smr's. The correct implementation separately sums seigniorage and taxes over the month, then computes the appropriate ratio once.

## **Proposal**
Sum seigniorage over the month (S)
Sum taxes over the month (T)
Return S / (S + T)

**Comment by dokwon** [comment]
Fixed by PR #45.
