### ISSUE TITLE
Key restore was broken from v0.2.1->v0.2.2

### ISSUE THREAD

**Issue by sriney-staked** [terra-project/core#191]
Description:  A MNEMONIC from a key created with v0.2.1 is not recoverable as the same key in v0.2.2 and vice versa.

**To Reproduce**
Steps to repro.  with v0.2.1 `terracli keys add Key0.2.1` then with MNEMONIC  on v0.2.2 do `terracli keys add Key0.2.2 --recover` and the key is different

This needs to be reverted/fixed  https://github.com/terra-project/core/pull/178

**Comment by YunSuk-Yeo** [comment]
solved by #193 except ledger

**Comment by dokwon** [comment]
@YunSuk-Yeo instead of a prompt asking the user to choose between two different wallet addresses, could we add a `--old-hd-path` option that defaults to the previous HD path? Likely more intuitive.
