### ISSUE TITLE
[FEATURE] query whole oracle data from one endpoint

### ISSUE THREAD

**Issue by dlguddus** [terra-project/core#192]
**Problem definition**
When we query any oracle data(votes, prevotes, prices), we need to query each denom. It takes quite a latency to query each denom, causing unnecessary latency

**Feature specification**
When we query any oracle data without denom flag, it returns data from all available denom.
Also, create endpoints for RPC so that oracle data can be queried from remote server.

**Comment by dokwon** [comment]
Will be incorporated in Columbus-3. Please follow the project board for progress.

**Comment by dlguddus** [comment]
Thanks. It will be very useful!

**Comment by dokwon** [comment]
@algok @brianTerra let's include this in the `fcd` implementation

**Comment by YunSuk-Yeo** [comment]
@dlguddus is it required to query whole (prevotes & votes) of all validators?

**Comment by dlguddus** [comment]
> @dlguddus is it required to query whole (prevotes & votes) of all validators?

yes. if not, it should be repeated for each validators. because the number of validators is limited, I think the whole data is not very heavy to transfer.
