### ISSUE TITLE
[BUG] Repository code language is shown as "Javascript" 

### ISSUE THREAD

**Issue by dokwon** [terra-project/core#194]
**Describe the bug**
The main language of the core repository is represented as Javascript on github. It should obviously be go. 

**To Reproduce**
NA 

**Context & versions**
NA 

**(if applicable) suggested solution**
https://hackernoon.com/how-to-change-repo-language-in-github-c3e07819c5bb

**Comment by YunSuk-Yeo** [comment]
Resolved by #203
