### ISSUE TITLE
[FEATURE] Align block rewards to be paid in SDT 

### ISSUE THREAD

**Issue by dokwon** [terra-project/core#199]
**Problem definition**

One of Terra's core value propositions is the stability of block rewards. In other words, by issuing block rewards irrespective of the source in stablecoin, the cash flow from a unit luna token is independent from the market price of Luna itself. This has some very nice properties that allow Luna staking to be less speculative, which is a serious incentive problem plaguing most proof of stake networks.

Problem is, block rewards currently are paid in many stablecoins and Luna. Tax fees and gas fees are paid in the denomination of the sender's choosing, and swap fees are paid in the denomination of the asset being asked for. 

**Feature specification**

We need to build a conversion layer that burns all stablecoins and Luna paid as fees, and then issues an equivalent value of SDT as fees instead. 

- For all fees involving coins other than `usdr`, instead of calling `auth.feeCollectionKeeper.AddFees()`, retrieve the latest swap rate between the asset and `usdr`. 
- If the swap rate exist, call `market.SwapCoins` on the asset to swap the asset to an equivalent value in usdr. Make sure to mark the swap for internal use to avoid paying swap fees. Then proceed to add the converted `usdr` to the feepool.  
- If the swap rate does not exist, (i.e. the oracle is not functioning correctly for some reason), then just add the original coins to the feepool. 

**Additional context**

Perhaps a more efficient way to align rewards in SDT is to align denominations as the rewards are about to be given out every block instead of when the fees are paid. Given sufficiently large volume of fees one could argue this could significantly save computation costs. 

This would obviously come at a tradeoff of having to fork the fee collection functionality in the cosmos-sdk `auth` module.  Seems much better in the long term.

**Comment by dokwon** [comment]
@YunSuk-Yeo likely would involve a lot of documentation changes

**Comment by YunSuk-Yeo** [comment]
We can customize distribution's BeginBlocker to change collected fee to SDT before allocation.
