### ISSUE TITLE
[BUG] terrad shuts down after sustained lcd operation

### ISSUE THREAD

**Issue by dokwon** [terra-project/core#202]
**Describe the bug**

`terrad` shuts down after sustained operation after a kernel error involving too many open files (terra dev set at 65535). Likely a tendermint error

**To Reproduce**

Keep the finder running for some extended period of time

**Context & versions**

`terrad` version 0.2.3 

**(if applicable) suggested solution**
Search tendermint issue board

**Comment by dokwon** [comment]
Potentially related issue: https://github.com/tendermint/tendermint/issues/1740 looks like it wad resolved by limiting the number of rpc connections

**Comment by hanjukim** [comment]
We've found `systemd` service does not follow limitation described in /etc/security/limits.conf.
Problem solved after adding following lines to service file.
```
[Service]
LimitNOFILE=65535
```
