### ISSUE TITLE
[FEATURE] Lower timeout_commit to 4 seconds

### ISSUE THREAD

**Issue by dokwon** [terra-project/core#205]
We propose lowering the `timeout-commit` parameter to 4 seconds from the current 5s. After monitoring the state of the columbus mainnet we believe this will lead to nearly 1 second reduction in block production times, while leading to negligible impact on validator availability. The goal should be to keep reducing the commit timeout until block production time sits near 3 seconds.

**Comment by joe-bowman** [comment]
This doesn't have to be done as part of a release, as it won't affect consensus - and not all nodes have to do it at the same time (the nodes to affect the change will cause blocks they propose to be quicker). Only benefit to tying to a fork is that it avoids unnecessary restarts.

**Comment by dokwon** [comment]
Closing as out of scope. Thanks @joe-bowman
