### ISSUE TITLE
[FEATURE] Automate release process with `goreleaser` 

### ISSUE THREAD

**Issue by dokwon** [terra-project/core#206]
We've been releasing terra core manually; should seek to automate this process via `goreleaser`.

**Comment by etienne-napoleone** [comment]
I see that goreleaser had been implemented in #77 but the circleci publish step [errors](https://circleci.com/gh/terra-project/core/929?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link_
My guess is that the GITHUB_TOKEN doesn't have necessary `repo` access on terra-project/core, thus 404ing when trying to push the files.

Not really easy to debug/try has it only happen during release.
Could it be possible to reissue a token with suffisent access and update the `GITHUB_TOKEN` env var in the circleci conf?

**Comment by hanjukim** [comment]
goreleaser has a problem with building binaries. `terracli` built by goreleaser won't have `build tags: netgo ledger` enabled.

**Comment by dokwon** [comment]
Closing; out of scope for columbus-3
