### ISSUE TITLE
[FEATURE] Request for Vodka testnet for columbus-3

### ISSUE THREAD

**Issue by brianTerra** [terra-project/core#215]
**Problem definition** 
Provide testnet for time-relavant feature test (vesting, undelegation, budget voting and seigniorage distribution).

**Feature specification**
Create Vodka testnet that has been shortened aging features.
1) Unbonding time shortened from 21 days to 5 min
2) Budget voting period shortened from 30 days to 6 hours
3) Epoch shortened from min 4weeks to min 1 week
4) Genesis with test vesting accounts

**Comment by joe-bowman** [comment]
Would it not make sense to scale these proportionally, so they remain constant relative to each other (i.e. if voting goes from 30d to 6 hours, unbonding should go from 21d to 4 hours)
