### ISSUE TITLE
[BUG] build failed

### ISSUE THREAD

**Issue by jacksoom** [terra-project/core#220]
**Describe the bug**
Bulid source code failed, looks like a go.mod Error

**To Reproduce**
1:git clone https://github.com/terra-project/core/
2:git checkout master
3:make

ERROR:
`

rm -rf ./dist
rm -rf ./build
go get github.com/rakyll/statik
verifying github.com/go-critic/go-critic@v0.0.0-20181204210945-1df300866540/go.mod: checksum mismatch
	downloaded: h1:G7mAYYxgmS0lVkHyy2hEOLQCFB0DlQFTMLWggykrydY=
	go.sum:     h1:+sE8vrLDS2M0pZkBk0wy6+nLdKexVDrl/jBqQOTDThA=
make: *** [get_tools] Error 1

`
**Context & versions**
go version go1.12.6 darwin/amd64
source tag : commit 3162406eeecfb7ecc299a4da0311d667f3ad5f1d (HEAD -> master, tag: v0.2.3, origin/master)

**Comment by YunSuk-Yeo** [comment]
Can you retry building after delete go.sum?

**Comment by jacksoom** [comment]
I repalced the problematic deps in go.mod, and  it works fine.
