### ISSUE TITLE
where is the document about how to pegged the SDR, USD, KRW, JPY, EUR, and CNY.

### ISSUE THREAD

**Issue by wade-liwei** [terra-project/core#245]
where is the document about how to pegged the SDR, USD, KRW, JPY, EUR, and CNY?

**Comment by YunSuk-Yeo** [comment]
you can see related research document in agora

https://agora.terra.money/t/how-terra-achieves-stability/32

**Comment by wade-liwei** [comment]
@YunSuk-Yeo 

Thank you.
