### ISSUE TITLE
How to get Terra-CNY on your chain ?

### ISSUE THREAD

**Issue by wade-liwei** [terra-project/core#246]
Now I have  100 yuan RMB, How can I get the pegged Terra-CNY on your chain ?

**Comment by YunSuk-Yeo** [comment]
Terra-CNY should registered by validators with oracle feature.

Validators will submit LUNA price vote denominated in Terra-CNY like 8.3CNY.
The chain will collect votes and make Terra-CNY market with weighted median price of the votes. 

Then, any one can swap other assets to Terra-CNY.

**Comment by wade-liwei** [comment]
so everyone buy Terra_CNY from the chain by LUNA?

right ?

**Comment by YunSuk-Yeo** [comment]
yes Terra_CNY will be minted and offer coins will be burned.

**Comment by wade-liwei** [comment]
Got it, very interesting.

If I just have some fiat currency,  So I have to buy some assets on the chain from the exchange ?

**Comment by wade-liwei** [comment]
Why the coin maybe not stable ?

**Comment by YunSuk-Yeo** [comment]
yes you have to buy it from the exchange. 

currently Terra_USD is not avaliable on the exchange, but you can buy Terra_SDR or Terra_KRW from several exchanges.

1. for stability you have to refer our research doc
