### ISSUE TITLE
can not run 

### ISSUE THREAD

**Issue by wade-liwei** [terra-project/core#248]
follow the doc: https://docs.terra.money/guide/deploy-testnet#create-genesis-file-and-start-the-network

root@31b7ff8205d4 bin]# ./terrad start
I[2019-10-09|02:58:28.911] Starting ABCI with Tendermint                module=main
panic: unrecognized concrete type name cosmos-sdk/MsgCreateValidator

**Comment by wade-liwei** [comment]
I[2019-10-09|03:07:10.492] Starting ABCI with Tendermint                module=main
ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**Comment by YunSuk-Yeo** [comment]
Did you ever try terrad start without generating genesis accounts or collecting gentxs
then try,
```
$ terrad unsafe-reset-all
```
and run again
@wade-liwei

**Comment by Frank-AFN** [comment]
Any progress for this problem? I still have this issue

**Comment by YunSuk-Yeo** [comment]
`validator set is nil in genesis and still empty after ` is genesis problem. You have to perform `add-genesis-account`, `gentx`, and `collect-gentxs` to deploy testnet. After doing all these, do `$ terrad unsafe-reset-all` and `$terrad start`

@Frank-AFN
