### ISSUE TITLE
[Full-node] I want to become full-node in mainnet 

### ISSUE THREAD

**Issue by perfecting** [terra-project/core#260]
How to become a full-node in mainnet? 
I copied launch repo's  genesis.json to ~/.terrad/config/genesis.json and replaced config.toml‘s persistent_peers value ,but I got a error "unrecognized concrete type name cosmos-sdk/MsgCreateValidator".Can you help me?

**Comment by YunSuk-Yeo** [comment]
you should use columbus-2 genesis in launch repo not columbus-1 genesis.json

**Comment by perfecting** [comment]
Thank you very much ! but I used  launch repo's seed nodes to replace config.toml's persistent_peers ,it was not working and I get a error,as follows:
E[2019-10-24|02:36:31.363] Couldn't connect to any seeds                module=p2p
E[2019-10-24|02:36:32.801] Error dialing peer                           module=p2p err="dial tcp 211.249.50.106:26656: connect: connection refused"

E[2019-10-24|02:37:01.559] Dialing failed                               module=pex addr=46bba3a2c615ea5b569f086344f932fa11e81c01@211.249.50.106:26656 err="dial tcp 211.249.50.106:26656: connect: connection refused" attempts=0
Can you help me ?

**Comment by YunSuk-Yeo** [comment]
The best way is just waiting until finding good peers. If it cannot connect to any peers, then restart terrad. Did you try to sync from some snapshot point? Here is the [site]( https://www.chainlayer.io) which provides data snapshot  @perfecting

**Comment by perfecting** [comment]
Thank you for your help .
@YunSuk-Yeo
