### ISSUE TITLE
[BUG] panic: stored supply should not have been nil

### ISSUE THREAD

**Issue by joesixpack** [terra-project/core#284]
**Describe the bug**
Trying to get the latest testnet running.  Modified config.toml and downloaded the genesis file.

**To Reproduce**
j@j-desktop:~$ terrad start
I[2019-11-20|14:26:44.777] starting ABCI with Tendermint                module=main
panic: stored supply should not have been nil

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/supply/internal/keeper.Keeper.GetSupply(0xc0001098f0, 0x1638580, 0xc000993370, 0x1648940, 0xc000116d20, 0x164bb40, 0xc000106380, 0xc0008db980, 0x1647a40, 0xc00003c098, ...)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/x/supply/internal/keeper/keeper.go:50 +0x18f
github.com/terra-project/core/x/treasury/internal/keeper.Keeper.RecordEpochInitialIssuance(0xc0001098f0, 0x1638580, 0xc0009933e0, 0xc0001098f0, 0x1638580, 0xc0009933b0, 0x16385c0, 0xc000993400, 0xc000b58020, 0x8, ...)
        /home/j/core/x/treasury/internal/keeper/keeper.go:180 +0x6c
github.com/terra-project/core/x/treasury.InitGenesis(0x1647a40, 0xc00003c098, 0x16596a0, 0xc000082a40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/j/core/x/treasury/genesis.go:19 +0x2b7
github.com/terra-project/core/x/treasury.AppModule.InitGenesis(0xc0001098f0, 0x1638580, 0xc0009933e0, 0xc0001098f0, 0x1638580, 0xc0009933b0, 0x16385c0, 0xc000993400, 0xc000b58020, 0x8, ...)
        /home/j/core/x/treasury/module.go:108 +0x155
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000120070, 0x1647a40, 0xc00003c098, 0x16596a0, 0xc000082a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/types/module/module.go:258 +0x278
github.com/terra-project/core/app.(*TerraApp).InitChainer(0xc0009d3c00, 0x1647a40, 0xc00003c098, 0x16596a0, 0xc000082a40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/j/core/app/app.go:261 +0x11d
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000150360, 0x0, 0xed451f260, 0x0, 0xc0004f75d0, 0xa, 0xc000082940, 0x2104690, 0x0, 0x0, ...)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/baseapp/baseapp.go:400 +0x2c7
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000b00a80, 0x0, 0xed451f260, 0x0, 0xc0004f75d0, 0xa, 0xc000082940, 0x2104690, 0x0, 0x0, ...)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/abci/client/local_client.go:223 +0x101
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc000566cc0, 0x0, 0xed451f260, 0x0, 0xc0004f75d0, 0xa, 0xc000082940, 0x2104690, 0x0, 0x0, ...)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/proxy/app_conn.go:65 +0x6b
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc001e8b0c0, 0xa, 0x0, 0x123f09f, 0x6, 0xc0004f75d0, 0xa, 0x0, 0x0, 0x0, ...)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/consensus/replay.go:311 +0x666
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc001e8b0c0, 0x165c1a0, 0xc000120460, 0x80, 0x10a5a60)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/consensus/replay.go:269 +0x485
github.com/tendermint/tendermint/node.doHandshake(0x165b520, 0xc000010498, 0xa, 0x0, 0x123f09f, 0x6, 0xc0004f75d0, 0xa, 0x0, 0x0, ...)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/node/node.go:275 +0x199
github.com/tendermint/tendermint/node.NewNode(0xc000a123c0, 0x16422c0, 0xc0009c9720, 0xc0009937f0, 0x1627f00, 0xc0008987a0, 0xc000993a80, 0x143ee18, 0xc000993a90, 0x1648400, ...)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/node/node.go:582 +0x334
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000899ca0, 0x143f7c8, 0x1d, 0x0, 0x0)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/server/start.go:152 +0x4c1
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc00014d680, 0x2104690, 0x0, 0x0, 0x0, 0x0)
        /home/j/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.4/server/start.go:65 +0xb4
github.com/spf13/cobra.(*Command).execute(0xc00014d680, 0x2104690, 0x0, 0x0, 0xc00014d680, 0x2104690)
        /home/j/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00012e000, 0x12649ad, 0xc00087dea0, 0x5974d2)
        /home/j/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/j/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc00012e000, 0x143fbe8, 0x12498cb, 0x10)
        /home/j/go/pkg/mod/github.com/tendermint/tendermint@v0.32.7/libs/cli/setup.go:89 +0x3c
main.main()
        /home/j/core/cmd/terrad/main.go:71 +0x85c
j@j-desktop:~$

**Comment by YunSuk-Yeo** [comment]
I guess you didn't run `$terrad unsafe-reset-all` after downloading genesis.
Can you try it again with reset command?

**Comment by joesixpack** [comment]
I had, but it didn't make any difference.

**Comment by joesixpack** [comment]
Running that will reset the config and maybe genesis anyhow.

**Comment by YunSuk-Yeo** [comment]
Then, maybe the genesis has some problem. Can you check chain-id in the genesis?

**Comment by joesixpack** [comment]
Looks like the genesis is actually mainnet!  So here's what I did now:

sudo rm -rf .terrad
terrad unsafe-reset-all
rm /home/j/.terrad/config/genesis.json
terrad init --chain-id=soju-0011 soju-0011
terracli keys add validator
terrad add-genesis-account $(terracli keys show validator -a) 1000uluna,1000usdr
rm /home/j/.terrad/config/gentx/gentx-81e26bc5bc81598041459e7bbc91fa4e0c977cb3.json
terrad gentx --name validator --amount 100uluna
terrad collect-gentxs

Then edited config.toml with:

persistent_peers = "1e1677e4ed9acf4e28de40b67ac01554aed1a29e@52.78.69.160:26656"

Then:

j@j-desktop:~/.terrad/config$ terrad start
I[2019-11-21|09:42:03.945] starting ABCI with Tendermint                module=main
ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**Comment by YunSuk-Yeo** [comment]
To join soju-0011, you should download https://raw.githubusercontent.com/terra-project/networks/master/soju-0011/genesis.json

```
$ git checkout v0.3.0-rc2
$ make install
$ terrad unsafe-reset-all
$ wget https://raw.githubusercontent.com/terra-project/networks/master/soju-0011/genesis.json -O ~/.terrad/config/genesis.json
$ terrad start
```

@joesixpack 

The above command is for local testnet. To make your local testnet, you should give more than 1,000,000uluna at `gentx` command because `min-self-bond` = 1,000,000uluna

**Comment by YunSuk-Yeo** [comment]
Close inactive
