### ISSUE TITLE
[BUG] `/gov/proposals/<Proposal ID>/deposits` returns unexpected results on deposits

### ISSUE THREAD

**Issue by winslyn** [terra-project/core#297]
**Describe the bug**
`/gov/proposals/<Proposal ID>/deposits` returns unexpected results on deposits as below:

`curl http://localhost:1317/gov/proposals/10`
```
{
  "height": "135745",
  "result": {
    "content": {
      "type": "gov/TextProposal",
      "value": {
        "title": "kytzu testing ",
        "description": "Test proposal with 100 luna initial amount"
      }
    },
    "id": "10",
    "proposal_status": "Rejected",
    "final_tally_result": {
      "yes": "16000000000",
      "abstain": "0",
      "no": "0",
      "no_with_veto": "0"
    },
    "submit_time": "2019-11-30T13:09:03.613929831Z",
    "deposit_end_time": "2019-12-02T13:09:03.613929831Z",
    "total_deposit": [
      {
        "denom": "uluna",
        "amount": "100000000"
      }
    ],
    "voting_start_time": "2019-11-30T13:09:03.613929831Z",
    "voting_end_time": "2019-12-02T13:09:03.613929831Z"
  }
}
```
`curl http://localhost:1317/gov/proposals/10/deposits`
```
{
  "height": "0",
  "result": null
}
```

I thought it was perhaps due to pruning and tried older proposal.

`curl http://localhost:1317/gov/proposals/9`
```
{
  "height": "135761",
  "result": {
    "content": {
      "type": "gov/TextProposal",
      "value": {
        "title": "Test Proposal",
        "description": "My awesome proposal"
      }
    },
    "id": "9",
    "proposal_status": "Rejected",
    "final_tally_result": {
      "yes": "16000000000",
      "abstain": "0",
      "no": "0",
      "no_with_veto": "0"
    },
    "submit_time": "2019-11-30T06:20:04.357798584Z",
    "deposit_end_time": "2019-12-02T06:20:04.357798584Z",
    "total_deposit": [
      {
        "denom": "ukrw",
        "amount": "10"
      },
      {
        "denom": "uluna",
        "amount": "100000000"
      }
    ],
    "voting_start_time": "2019-11-30T13:10:07.385670079Z",
    "voting_end_time": "2019-12-02T13:10:07.385670079Z"
  }
}
```
`curl http://localhost:1317/gov/proposals/9/deposits`
```
{
  "height": "0",
  "result": [
    {
      "proposal_id": "9",
      "depositor": "terra1kuwhf23p8n5k34e0j76qyfplfs63jpzkl2srmv",
      "amount": [
        {
          "denom": "uluna",
          "amount": "1000000"
        }
      ]
    },
    {
      "proposal_id": "9",
      "depositor": "terra1kuwhf23p8n5k34e0j76qyfplfs63jpzkl2srmv",
      "amount": [
        {
          "denom": "uluna",
          "amount": "99000000"
        }
      ]
    }
  ]
}
```

`/gov/proposals/9/deposits` returns deposits for only `uluna` while `/gov/proposals/9` returns `uluna` and `ukrw`.

And again `/gov/proposals/<Proposal ID>/deposits` for `7` and `8` returns `null` while from `/gov/proposals/<Proposal ID>` returns a deposit for `10000000 uluna`.
`curl http://localhost:1317/gov/proposals/8/deposits`
```
{
  "height": "0",
  "result": null
}
```
`curl http://localhost:1317/gov/proposals/7/deposits`
```
{
  "height": "0",
  "result": null
}
```

From `https://soju-lcd.terra.dev/gov/proposals/<Proposal ID>/deposits`, all of `10`, `9`, `8`, and `7` returns `null` when `localhost` returns `uluna` deposits for `9`.

`curl https://soju-lcd.terra.dev/gov/proposals/10/deposits`
```
{
  "height": "0",
  "result": null
}
```

The localhost lcd is running on `v0.3.0-rc3`.

What seems to be the problems:

(1) `/gov/proposals/<Proposal ID>/deposits` returns `null` while `/gov/proposals/<Proposal ID>` returns the initial deposit.

(2) `/gov/proposals/<Proposal ID>` seems including other denoms such as `ukrw` but `/gov/proposals/<Proposal ID>/deposits` does not.

(3) `/gov/proposals/<Proposal ID>/deposits` from `localhost` and `soju-lcd.terra.dev` returns different results.

**Comment by YunSuk-Yeo** [comment]
@winslyn 

(1) For the proposals which is got sufficient deposits but not passed, the deposits will be deleted(refund or burned) in the store. So the `/gov/proposals/<Proposal ID>/deposits` endpoint returns null, but SDK do not delete proposal itself if the proposal has enough deposits.

(2) I don't know how you got the deposit list for the `Rejected` proposal. The expected result is null, but your output was showing `uluna` deposits. One more wired thing is that the deposit from the same address and same proposal id should be combined. How do we reproduce this case?

(3) same issue with problem (2). Hmm I don't know how your node has deposit list of proposal 9.

**Comment by winslyn** [comment]
Thanks for looking into this.

(1) As you suggested, `/txs?message.action=deposit&proposal_deposit.proposal_id=<Proposal ID>` provides what I need.

(2) I looked into this and I was also surprised that I proposed the proposal 9 from an address `terra10993luwlar59q7syh7t3hhk0kmtee645vs3kev` but deposits returned a complete different result.

`curl http://localhost:1317/gov/proposals/9/proposer`
```
{
  "height": "0",
  "result": {
    "proposal_id": "9",
    "proposer": "terra10993luwlar59q7syh7t3hhk0kmtee645vs3kev"
  }
}
```

`curl http://localhost:1317/gov/proposals/9/deposits`
```
{
  "height": "0",
  "result": [
    {
      "proposal_id": "9",
      "depositor": "terra1kuwhf23p8n5k34e0j76qyfplfs63jpzkl2srmv",
      "amount": [
        {
          "denom": "uluna",
          "amount": "1000000"
        }
      ]
    },
    {
      "proposal_id": "9",
      "depositor": "terra1kuwhf23p8n5k34e0j76qyfplfs63jpzkl2srmv",
      "amount": [
        {
          "denom": "uluna",
          "amount": "99000000"
        }
      ]
    }
  ]
}
```
And I'm afraid I wasn't able to reproduce this on `soju-0013`. But I will certainly let you know if this happens again.

Thanks!
