### ISSUE TITLE
[BUG] `terracli keys add <NAME> --ledger` throws `ERROR: address rejected`

### ISSUE THREAD

**Issue by winslyn** [terra-project/core#309]
**Describe the bug**
`terracli keys add <NAME> --ledger` throws `ERROR: address  rejected` while `terracli keys add <NAME>` works without the error.

**To Reproduce**
`terracli keys add <NAME> --ledger`

**Context & versions**
```
$ terracli version --long
name: terra
server_name: terrad
client_name: terracli
version: 0.3.1
commit: 4fc37aa2220191317d67f6a9effc18239abd9269
build_tags: netgo,ledger
go: go version go1.13.4 darwin/amd64

```
**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by YunSuk-Yeo** [comment]
It is because the coin type. 

To prevent this in core v0.3.1, you have to install [ledger-terra v1.0.0](https://github.com/terra-project/ledger-terra/releases/tag/v1.0.0)

**Comment by winslyn** [comment]
Thanks!
