### ISSUE TITLE
Terra Station - Staking return 

### ISSUE THREAD

**Issue by barzinski** [terra-project/core#366]
The staking return is based on the total supply of Luna, which can be somewhat misleading to believe that the commitment is low.

I suggest it is based on the circulating supply or both.

**Comment by YunSuk-Yeo** [comment]
I think [station repo](https://github.com/terra-project/station) is proper place to discuss it. Anyway as I know, it is based on [total staked luna](https://lcd.terra.dev/staking/pool).
