### ISSUE TITLE
Merge tracking branch

### ISSUE THREAD

**Issue by hanjukim** [terra-project/core#368]
**Problem definition**
In tracking branch we have features:

1. treasury event log to each block which includes tax_rate, tax_cap. It is used for calculating gas and tax
2. protection code for preventing out of memory by querying txs
3. LCD endpoint: /treasury/indicators 
4. tracking all accounts for making rich list

This is painful to maintain different branch. It would be great if we merge these features into next release.

**Feature specification**
All of features seems possible to be merged since we have --tracking parameter for tracking all accounts which includes heavy loads

**Comment by YunSuk-Yeo** [comment]
hmm I agree on 3, and partially 4.
4. It can be done with export feature and I think this is more safe way to get chain snapshot state.

But the other features are not that necessary.

1. It can be replaced with update event of the end blocker. We always emit update `policy_update` and `tax_rate_update` events whenever the tax rate changes happen.
2. In some cases, full node operator may want to use querying txs without any restriction about the accounts, which are known to the operator.

**Comment by hanjukim** [comment]
@YunSuk-Yeo 
1. were `policy_update` and `tax_rate_update` in Columbus-3? We will have to reflect this to FCD collector @maruf0011 
2. let's make a parameter for enabling this feature.
3. merge to develop
4. I agree

**Comment by maruf0011** [comment]
its possible watch for `policy_update` and `tax_rate_update`. But about historical data?

**Comment by hanjukim** [comment]
> it's possible to watch for `policy_update` and `tax_rate_update`. But what about historical data?

We can keep recent tax rate and tax cap until `policy update` or `tax_rate_update` event emit.
