### ISSUE TITLE
about using rest api "/txs"

### ISSUE THREAD

**Issue by 17621859515** [terra-project/core#386]
--------------request body---------------
{
  "tx": {
    "msg": [
      {
        "type": "bank/MsgSend",
        "value": {
          "from_address": "terra1ehn20npy9jhf6mhryvk8am7xmtk2xsjx5dl7wk",
          "to_address": "terra1fr6c4my0euhfepm7e87w8c2l66n9khnwms5ske",
          "amount": [
            {
              "denom": "uluna",
              "amount": "10"
            }
          ]
        }
      }
    ],
    "fee": {
      "amount": [
        {
          "denom": "uluna",
          "amount": "1000"
        }
      ],
      "gas": "200000"
    },
    "signatures": {
      "signature": "+idS3aPGH21HBzTqiLB/d4ubKi102Tlt01Ig6Ig/FJFqd8K2AK1TUZm8YO7xqKB6vDZPGjed/36FggEqATzn4w==",
      "pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "AuN9dg0QDRl0wBsluqB/GixNae7jN1wu6+AM0HjxGk+R"
      },
      "account_number": "1886637",
      "sequence": "0"
    },
    "memo": ""
  },
  "mode": "block"
}

--------------resp---------------
{
  "height": "0",
  "txhash": "B02A35F98631E97FEB7D5B4CADF01C321EF961C1F6552F1B42D08AFACC5B243C",
  "code": 4,
  "raw_log": "{\"codespace\":\"sdk\",\"code\":4,\"message\":\"signature verification failed; verify correct account sequence and chain-id\"}" ,
  "gas_used": "19215"
}

how can I use /txs to avoid this error

**Comment by YunSuk-Yeo** [comment]
Did you set the chain-id as columbus-3 at signing? Which signing code are you using? @17621859515

**Comment by 17621859515** [comment]
> Did you set the chain-id as columbus-3 at signing? Which signing code are you using? @17621859515


tes, chainid is “columbus-3”
the signature algorithm uses "cosmos" sdk

**Comment by maczniak** [comment]
You may have solved this issue. I guess that `"sequence": "0"` was invalid.
> The sequence number is expected to increment every time a message is signed by a given account.

**Comment by hanjukim** [comment]
sequence 0 is valid for the initial transaction.

**Comment by gaozhengxin** [comment]
Same issue.
I build tx with cosmos-sdk v0.39.2, I make sign bytes by `auth.StdSignBytes(ChainID, accountNumber, sequence, fee, msgs, memo)`
This is my post data
```json
{
"tx":{
"fee":{"amount":[{"amount":"50000","denom":"uluna"}],"gas":"300000"},
"memo":"",
"msg":[{"type":"bank/MsgSend","value":{"amount":[{"amount":"100000","denom":"uluna"}],"from_address":"terra1wr965945fxexk68mxne5en56pr6la006p7764e","to_address":"terra1wr965945fxexk68mxne5en56pr6la006p7764e"}}],"signatures":[{"account_number":"29325","pub_key":{"type":"tendermint/PubKeySecp256k1","value":"A2aTt2EszZLw7FfmKqUcctepeMSHHEgsvyqJZXW/Z6ww"},"sequence":"0","signature":"dD8UyZbWbYqMg5l+yc5pvFp7iIWQFcOm4Le5rP4z3sg8OLBrsd/PLfiI/HCfVWghTDm1t24ltr5mwAF9H7wvGw=="}]
},
"mode":"block"
}
```

**Comment by gaozhengxin** [comment]
> Same issue.
> I build tx with cosmos-sdk v0.39.2, I make sign bytes by `auth.StdSignBytes(ChainID, accountNumber, sequence, fee, msgs, memo)`
> This is my post data
> 
> ```json
> {
> "tx":{
> "fee":{"amount":[{"amount":"50000","denom":"uluna"}],"gas":"300000"},
> "memo":"",
> "msg":[{"type":"bank/MsgSend","value":{"amount":[{"amount":"100000","denom":"uluna"}],"from_address":"terra1wr965945fxexk68mxne5en56pr6la006p7764e","to_address":"terra1wr965945fxexk68mxne5en56pr6la006p7764e"}}],"signatures":[{"account_number":"29325","pub_key":{"type":"tendermint/PubKeySecp256k1","value":"A2aTt2EszZLw7FfmKqUcctepeMSHHEgsvyqJZXW/Z6ww"},"sequence":"0","signature":"dD8UyZbWbYqMg5l+yc5pvFp7iIWQFcOm4Le5rP4z3sg8OLBrsd/PLfiI/HCfVWghTDm1t24ltr5mwAF9H7wvGw=="}]
> },
> "mode":"block"
> }
> ```


I found my signing string has the msg type "cosmos-sdk/MsgSend". It pass validation when I modified msg type to "bank/MsgSend". Strange as I have registered bank/MsgSend to my codec.
```json
{"account_number":"29325","chain_id":"tequila-0004","fee":{"amount":[{"amount":"50000","denom":"uluna"}],"gas":"300000"},"memo":"","msgs":[{"type":"cosmos-sdk/MsgSend","value":{"amount":[{"amount":"100000","denom":"uluna"}],"from_address":"terra1wr965945fxexk68mxne5en56pr6la006p7764e","to_address":"terra1wr965945fxexk68mxne5en56pr6la006p7764e"}}],"sequence":"0"}
```
