### ISSUE TITLE
[FEATURE] Add unsafe-cors flag 

### ISSUE THREAD

**Issue by YunSuk-Yeo** [terra-project/core#409]
**Problem definition**
Add a flag to the rest server that if a service provider is fine with accepting all cors.

**Feature specification**
https://github.com/cosmos/cosmos-sdk/pull/5671

**Comment by hanjukim** [comment]
I can see --unsafe-cors from `terracli rest-server --help` and LocalTerra is using it now. Can we close this issue?

**Comment by YunSuk-Yeo** [comment]
It has the flag but we need to apply that flag option to rest-server instance. I did it on the above PR
