### ISSUE TITLE
[BUG] Validate genesis

### ISSUE THREAD

**Issue by oggy95** [terra-project/core#418]
**Describe the bug**
Upgrading terrad and terracli fron 0.3.6 to 0.4.0. Trying to start network columbus-4 and when validate genesis, got an error::
`ERROR: error validating genesis file /root/.terrad/config/genesis.json: invalid account found in genesis state; address: terra1fs7mmpducjf25j70sk3sz6k5phz2fllmyr5gwz, error: vesting total ratio must be one`

**To Reproduce**
1. Upgrade terrad and terracli to v0.4.0.
2. `terrad unsafe-reset-all`
3. Download new genesis (get from this https://github.com/terra-project/mainnet) and replace old.
4. `terrad validate-genesis`

**Context & versions**
```
name: terra
server_name: terrad
client_name: terracli
version: 0.4.0
commit: 0ccb97e4427007f940b611fb0b5fb67d6a7d69f5
build_tags: netgo,ledger
go: go version go1.13.1 linux/amd64

```
```
name: terra
server_name: terrad
client_name: terracli
version: 0.4.0
commit: 0ccb97e4427007f940b611fb0b5fb67d6a7d69f5
build_tags: netgo,ledger
go: go version go1.13.1 linux/amd64

```

**Comment by YunSuk-Yeo** [comment]
Please use genesis in https://github.com/terra-project/mainnet/tree/master/columbus-4

@oggy95

**Comment by YunSuk-Yeo** [comment]
and you can verify your genesis is correct with 

```
$ jq -S -c -M "" genesis.json | shasum -a 256
bb658924c74770f0c0314b2774f63a1925e981f6639ae72a87d521d4306729f5 genesis.json
```

**Comment by oggy95** [comment]
Updated version golang to 1.14.1, downloaded genesis, verified it (while verifying got this message)
```
jq -S -c -M "" genesis.json | shasum -a 256
bb658924c74770f0c0314b2774f63a1925e981f6639ae72a87d521d4306729f5  -
```
But error still exist

**Comment by hanjukim** [comment]
I can re-produce the problem too. We are looking into it.

**Comment by YunSuk-Yeo** [comment]
Many case we use script language to generate vesting schedules. However using other language decimal data types always causes precision error.

Ex)

When we assume there are
```
17 vesting schedules releasing 5.5% 
1 vesting schedule releasing 6.5%

total = 100%
```

### In Python
The final element is normally calculated by subtracting addition of all other values from the 1.
```
1 vesting schedule releasing 6.5% = 1 - 17 * 0.055 = 0.064999999999999610
```

Total is also 1
```
total = 0.055 * 17 + 0.064999999999999610
```

### In GoLang sdk.Dec
When you took those values to GoLang we will get 0.999999999999999610 as sum of all schedules.

**Comment by YunSuk-Yeo** [comment]
So propose to do minor precision correction in vesting schedule validation step by rounding in 6 or 9th decimal digits
