### ISSUE TITLE
[BUG] Unknown name wasm

### ISSUE THREAD

**Issue by eugenio53390** [terra-project/core#421]
**Describe the bug**
When I tried to start terrad on my vm the program has written in the bash "panic: Unknown name wasm".

**To Reproduce**
It isn't reproducible i think.

**Context & versions**

terrad version: 0.3.5
Go-lang version: 1.13.3 
terracli version: 0.3.5

Proofs:
![image](https://user-images.githubusercontent.com/18421572/97480504-c8fdfa80-1953-11eb-862b-81cdf3a829e1.png)

**Comment by hanjukim** [comment]
version of terrad should be higher than 0.4.0
