### ISSUE TITLE
[FEATURE] How to add a logo to the terra node

### ISSUE THREAD

**Issue by lucabranda** [terra-project/core#424]
How can I add a logo to my Terra node? I can't find any tutorial on how to do this. 
Thanks

**Comment by MissionControlValidator** [comment]
I have the same problem

**Comment by YunSuk-Yeo** [comment]
To update validator image, you can add Keybase identity to your validator details

```
$ terracli tx staking edit-validator -h
...
    --identity string              The (optional) identity signature (ex. UPort or Keybase) (default "[do-not-modify]")
```

**Comment by YunSuk-Yeo** [comment]
I just close the issue for clean up purpose. 
Please feel free to reopen the issue
