### ISSUE TITLE
[BUG] Out of gas causes panic when external contract store query executed

### ISSUE THREAD

**Issue by YunSuk-Yeo** [terra-project/core#431]
**Describe the bug**
Core uses gas meter to limit unexpected query DDoS attacks to protect node operators from the external contract query. However, gas meter was made for Tx execution process, so it just occurs panic instead of clean error. 

**To Reproduce**
set query_gas_limit = 0 in wasm.toml and execute query contract-store 

**Context & versions**
v0.4.0

**(if applicable) suggested solution**
Append recover statement before executing external query

**Comment by alpe** [comment]
@YunSuk-Yeo you probably want this fix upstream in wasmd to be safe in the future. Please be so kind and open issues in the wasmd repo as well for the 🐛  🐛 . 
Share and care. We generally appreciate any issues/ feedback.  ❤️ 
I have  opened an [issue](https://github.com/CosmWasm/wasmd/issues/321) for this.

**Comment by YunSuk-Yeo** [comment]
@alpe got it I will keep share the problem we can help wasmd.
