### ISSUE TITLE
[BUG] "https://station.terra.money/contracts" cannot send tokens along with transaction

### ISSUE THREAD

**Issue by shravanshetty1** [terra-project/core#579]
When I use the "Interact" button to run a transaction i can run it as long as I dont send tokens along with the transaction.

If i send tokens along with the transaction i get the console error -

> CreateTxFailed: this transaction cannot be broadcasted via legacy REST endpoints, because it does not support Amino serialization. Please either use CLI, gRPC, gRPC-gateway, or directly query the Tendermint RPC endpoint to broadcast this transaction. The new REST endpoint (via gRPC-gateway) is POST /cosmos/tx/v1beta1/txs. Please also see the REST endpoints migration guide at https://docs.cosmos.network/master/migrations/rest.html for more info

**Comment by YunSuk-Yeo** [comment]
That errors occurs when your tx is wrong formatted. so simply failed to decode your tx. 

can you post your tx?
