### ISSUE TITLE
how to build on windows?

### ISSUE THREAD

**Issue by problemhacked** [terra-project/core#63]
On Windows10, I executed

git clone -b develop --single-branch https://github.com/terra-project/core 

in c:/go/src

and  executed

go build

in c:/go/src/core

then there is a message like :

can't load package: package github.com/terra-project/core: unknown import path "github.com/terra-project/core": cannot find module providing package github.com/terra-project/core

**Comment by YunSuk-Yeo** [comment]
How about
`go build ./...`?

**Comment by problemhacked** [comment]
> How about
> `go build ./...`?
go build all !
success, thank you

**Comment by dokwon** [comment]
Windows build overall needs an overhaul. Let's open a pull request to refurbish the windows deployment pipeline.

**Comment by dokwon** [comment]
Seems like a solved problem by now, let me know if the issue persists.
