### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ghost** [terra-project/core#66]
when i use 'make'  command

(60/60) Wrote gonum.org/v1/gonum@master
go install -tags "netgo" -ldflags "-X github.com/terra-project/terra/version.Version=0.0.3-201-g7105278 -X terra/version.Version=0.0.3-201-g7105278" ./cmd/terrad
cmd/terrad/main.go:22:2: cannot find package "terra/app" in any of:
	/home/eunsung/go/src/core/vendor/terra/app (vendor tree)
	/usr/lib/go-1.10/src/terra/app (from $GOROOT)
	/home/eunsung/go/src/terra/app (from $GOPATH)
cmd/terrad/main.go:23:2: cannot find package "terra/cmd/init" in any of:
	/home/eunsung/go/src/core/vendor/terra/cmd/init (vendor tree)
	/usr/lib/go-1.10/src/terra/cmd/init (from $GOROOT)
	/home/eunsung/go/src/terra/cmd/init (from $GOPATH)
cmd/terrad/main.go:6:2: cannot find package "terra/types/util" in any of:
	/home/eunsung/go/src/core/vendor/terra/types/util (vendor tree)
	/usr/lib/go-1.10/src/terra/types/util (from $GOROOT)
	/home/eunsung/go/src/terra/types/util (from $GOPATH)
cmd/terrad/main.go:7:2: cannot find package "terra/version" in any of:
	/home/eunsung/go/src/core/vendor/terra/version (vendor tree)
	/usr/lib/go-1.10/src/terra/version (from $GOROOT)
	/home/eunsung/go/src/terra/version (from $GOPATH)
Makefile:39: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by dokwon** [comment]
@ghost What machine are you running this on? (Windows, mac, etc)

**Comment by winslyn** [comment]
Your PATH is wrong.

Try 
```
cd /home/eunsung/go/src/
git clone https://github.com/terra-project/core/ terra
make
```

**Comment by dokwon** [comment]
Closing issue. Let us know if there's additional issues.
