### ISSUE TITLE
How can i join testnet?

### ISSUE THREAD

**Issue by SeongKuk** [terra-project/core#74]
Hello, Terra-project team.

I want to connect terra testnet(soju-0006).

So, i built terra core from master branch and performed "terrad init {myname}".

And i changed ~/.terra/config/genesis.json to genesis.json of soju-0006 (https://github.com/terra-project/networks/blob/master/soju-0006/genesis.json).

Also i added seeds and persistent_peers at config.toml

But my terra node can not connect to soju-0006...

How can i join testnet?

P.S. I can not access at https://explorer.terra.money/validators

E[2019-04-11|02:19:09.692] Dialing failed                               module=pex addr=7200fdd01a07e87f39855b825b00455f3eb290ca@52.196.51.41:26656 err="auth failure: secrect conn failed: EOF" attempts=0
E[2019-04-11|02:19:09.696] Dialing failed                               module=pex addr=b4663211d8fada08e6684f6668b9c0a2a750ec6b@54.199.251.19:26656 err="auth failure: secrect conn failed: EOF" attempts=0
E[2019-04-11|02:19:09.697] Dialing failed                               module=pex addr=586462592551c4c60ec9fffd76a898b3082c6858@54.248.60.232:26656 err="auth failure: secrect conn failed: EOF" attempts=0
E[2019-04-11|02:19:09.697] Dialing failed                               module=pex addr=cd2623c92ccd714647773685fee9bae5b7ba58ef@54.199.196.117:26656 err="auth failure: secrect conn failed: EOF" attempts=0
E[2019-04-11|02:19:10.401] Error dialing peer                           module=p2p err="auth failure: secrect conn failed: EOF"
E[2019-04-11|02:19:11.955] Error dialing peer                           module=p2p err="auth failure: secrect conn failed: EOF"
E[2019-04-11|02:19:12.273] Error dialing peer                           module=p2p err="auth failure: secrect conn failed: EOF"
E[2019-04-11|02:19:12.319] Error dialing peer                           module=p2p err="auth failure: secrect conn failed: EOF"
E[2019-04-11|02:19:39.692] Dialing failed                               module=pex addr=7200fdd01a07e87f39855b825b00455f3eb290ca@52.196.51.41:26656 err="auth failure: secrect conn failed: EOF" attempts=1
E[2019-04-11|02:19:39.697] Dialing failed                               module=pex addr=cd2623c92ccd714647773685fee9bae5b7ba58ef@54.199.196.117:26656 err="auth failure: secrect conn failed: EOF" attempts=1
E[2019-04-11|02:19:39.697] Dialing failed                               module=pex addr=586462592551c4c60ec9fffd76a898b3082c6858@54.248.60.232:26656 err="auth failure: secrect conn failed: EOF" attempts=1
E[2019-04-11|02:19:39.697] Dialing failed                               module=pex addr=b4663211d8fada08e6684f6668b9c0a2a750ec6b@54.199.251.19:26656 err="auth failure: secrect conn failed: EOF" attempts=1
E[2019-04-11|02:20:09.692] Dialing failed                               module=pex addr=7200fdd01a07e87f39855b825b00455f3eb290ca@52.196.51.41:26656 err="auth failure: secrect conn failed: EOF" attempts=2
E[2019-04-11|02:20:09.696] Dialing failed                               module=pex addr=cd2623c92ccd714647773685fee9bae5b7ba58ef@54.199.196.117:26656 err="auth failure: secrect conn failed: EOF" attempts=2
E[2019-04-11|02:20:09.696] Dialing failed                               module=pex addr=586462592551c4c60ec9fffd76a898b3082c6858@54.248.60.232:26656 err="auth failure: secrect conn failed: EOF" attempts=2
E[2019-04-11|02:20:09.696] Dialing failed                               module=pex addr=b4663211d8fada08e6684f6668b9c0a2a750ec6b@54.199.251.19:26656 err="auth failure: secrect conn failed: EOF" attempts=2
E[2019-04-11|02:20:39.692] Dialing failed                               module=pex addr=7200fdd01a07e87f39855b825b00455f3eb290ca@52.196.51.41:26656 err="auth failure: secrect conn failed: EOF" attempts=3
E[2019-04-11|02:20:39.696] Dialing failed                               module=pex addr=cd2623c92ccd714647773685fee9bae5b7ba58ef@54.199.196.117:26656 err="auth failure: secrect conn failed: EOF" attempts=3
E[2019-04-11|02:20:39.696] Dialing failed                               module=pex addr=b4663211d8fada08e6684f6668b9c0a2a750ec6b@54.199.251.19:26656 err="auth failure: secrect conn failed: EOF" attempts=3
E[2019-04-11|02:20:39.697] Dialing failed                               module=pex addr=586462592551c4c60ec9fffd76a898b3082c6858@54.248.60.232:26656 err="auth failure: secrect conn failed: EOF" attempts=3
E[2019-04-11|02:21:09.692] Dialing failed                               module=pex addr=7200fdd01a07e87f39855b825b00455f3eb290ca@52.196.51.41:26656 err="auth failure: secrect conn failed: EOF" attempts=4
E[2019-04-11|02:21:09.696] Dialing failed                               module=pex addr=b4663211d8fada08e6684f6668b9c0a2a750ec6b@54.199.251.19:26656 err="auth failure: secrect conn failed: EOF" attempts=4
E[2019-04-11|02:21:09.696] Dialing failed                               module=pex addr=cd2623c92ccd714647773685fee9bae5b7ba58ef@54.199.196.117:26656 err="auth failure: secrect conn failed: EOF" attempts=4
E[2019-04-11|02:21:09.697] Dialing failed                               module=pex addr=586462592551c4c60ec9fffd76a898b3082c6858@54.248.60.232:26656 err="auth failure: secrect conn failed: EOF" attempts=4
E[2019-04-11|02:21:15.523] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=586462592551c4c60ec9fffd76a898b3082c6858@54.248.60.232:26656 elapsed=2m3.249245147s
E[2019-04-11|02:21:21.549] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=cd2623c92ccd714647773685fee9bae5b7ba58ef@54.199.196.117:26656 elapsed=2m9.230493235s
E[2019-04-11|02:21:22.503] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=b4663211d8fada08e6684f6668b9c0a2a750ec6b@54.199.251.19:26656 elapsed=2m12.10110046s
E[2019-04-11|02:21:23.689] Failed to reconnect to peer. Beginning exponential backoff module=p2p addr=7200fdd01a07e87f39855b825b00455f3eb290ca@52.196.51.41:26656 elapsed=2m11.734292071s

**Comment by dokwon** [comment]
Hey, explorer validators page is something that is specific to Cosmos Hub. Our Finder is online at finder.terra.money. Can you try again with the same set of seeds?

**Comment by SeongKuk** [comment]
Thanks for fast feedback.

I tried again but i received error message..

[2019-04-11|07:19:37.227] Starting ABCI with Tendermint                module=main 
E[2019-04-11|07:19:37.287] Dialing failed                               module=pex addr=586462592551c4c60ec9fffd76a898b3082c6858@54.248.60.232:26656 err="auth failure: secrect conn failed: EOF" attempts=0
I[2019-04-11|07:19:37.622] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[2019-04-11|07:19:37.625] Committed state                              module=state height=1 txs=0 appHash=31B158C181E21F1615D0E49CCBF1EF04D1AA4F22AB3B82628F48F24D64E1EC48
panic: Panicked questionably: Failed to process committed block (2:A0ABEB4AD347B1AFCAB0D9E39D875B22AFA93FCCB1EC38843F2C90CB87E3F059): Wrong Block.Header.AppHash.  Expected 31B158C181E21F1615D0E49CCBF1EF04D1AA4F22AB3B82628F48F24D64E1EC48, got 0452C69A04AD625C90E3547D810937E4521039DBF4EB76E72E16186EE70B004D

goroutine 77 [running]:
terra/vendor/github.com/tendermint/tendermint/libs/common.PanicQ(...)
	/home/ubuntu/go/src/terra/vendor/github.com/tendermint/tendermint/libs/common/errors.go:245
terra/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000a0e1a0)
	/home/ubuntu/go/src/terra/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:341 +0x19a0
created by terra/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/home/ubuntu/go/src/terra/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:118 +0x84

**Comment by YunSuk-Yeo** [comment]
Current testnet(soju-0007) is working on v0.0.7 release. Please use v0.0.7 release. 

1. Change genesis.json to new version of soju-0007.
2. Please refer https://github.com/terra-project/networks/tree/master/soju-0007 to check seeds.
3. Before change network, run $terrad unsafe-reset-all

**Comment by dokwon** [comment]
Closing issue. Let me know if there's any problems.
