### ISSUE TITLE
fee amount is null but paid

### ISSUE THREAD

**Issue by wlsaud619** [terra-project/core#82]
### **Summary.**
I didn't set the fee when I sent the tx.
The fee is **Null** but paid(1000mluna).

### **Terra Version.**
`terrad version --long`
> cosmos-sdk: 0.0.7-5-g2fb73e4
> git commit:
> vendor hash:
> build tags:
> go version go1.12.1 linux/amd64

### **Steps.**

**1.` terracli q account terra1nvtzp6jk50q734lpvsxf84d3pezg85p8lqgnyf --chain-id=soju-0007 --output=json | jq`**

> {
>   "type": "auth/Account",
>   "value": {
>     "address": "terra1nvtzp6jk50q734lpvsxf84d3pezg85p8lqgnyf",
>     "coins": [
>       {
>         "denom": "mluna",
>         "amount": "10000000"
>       }
>     ],
>     "public_key": null,
>     "account_number": "39",
>     "sequence": "0"
>   }
> }

**2. `terracli tx send terra1tusfpgvjrplqg2fm7wacy4slzjmnzswcfn9puj 1000000mluna --from=J $chain`**

> {"chain_id":"soju-0007","account_number":"39","sequence":"0","fee":{"amount":null,"gas":"200000"},"msgs":[{"type":"cosmos-sdk/MsgSend","value":{"from_address":"terra1nvtzp6jk50q734lpvsxf84d3pezg85p8lqgnyf","to_address":"terra1tusfpgvjrplqg2fm7wacy4slzjmnzswcfn9puj","amount":[{"denom":"mluna","amount":"1000000"}]}}],"memo":""}

_"fee":{"amount":null,"gas":"200000"},"_

**3. `terracli q account terra1nvtzp6jk50q734lpvsxf84d3pezg85p8lqgnyf --chain-id=soju-0007 --output=json | jq`**

> {
>   "type": "auth/Account",
>   "value": {
>     "address": "terra1nvtzp6jk50q734lpvsxf84d3pezg85p8lqgnyf",
>     "coins": [
>       {
>         "denom": "mluna",
>         "amount": "8999000"
>       }
>     ],
>     "public_key": {
>       "type": "tendermint/PubKeySecp256k1",
>       "value": "A0HT0WtwAFbNtkm1T7AQ6w2xJpVjDKRhyaHK4DzJSfWx"
>     },
>     "account_number": "39",
>     "sequence": "1"
>   }
> }
>

**Comment by dokwon** [comment]
So Terra Core has two types of fees: 

- Compute fees: similar to network gas, and is set by validators
- Stability fees: charges a small percentage of transactions (at genesis, I think set to 0.1% of the transaction CAPPED at the value of 1 Terra SDR) 

The fees you mention are compute layer fees, and indeed that has not been properly set by most soju 007 validators, and so your tx made it into the mempool. 

You still payed 0.1% stability fees, (in our nomenclature, tax), which is why you are seeing the 1000mLuna expenditure. 

Let me know if you have more questions.

**Comment by wlsaud619** [comment]
> So Terra Core has two types of fees:
> 
> * Compute fees: similar to network gas, and is set by validators
> * Stability fees: charges a small percentage of transactions (at genesis, I think set to 0.1% of the transaction CAPPED at the value of 1 Terra SDR)
> 
> The fees you mention are compute layer fees, and indeed that has not been properly set by most soju 007 validators, and so your tx made it into the mempool.
> 
> You still payed 0.1% stability fees, (in our nomenclature, tax), which is why you are seeing the 1000mLuna expenditure.
> 
> Let me know if you have more questions.

Thanks for the friendly explanation!
